name: poke_point
description: Check In mobile App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  http: ^0.13.1
  fluttertoast: ^7.1.8
  sqflite: ^1.2.1
  flutter_login: ^2.0.0
  connectivity: ^3.0.3
  google_maps_flutter: ^0.5.24+1
  geolocator: ^5.3.0
  cupertino_icons: ^1.0.2
  #flutter_nfc_kit: ^2.2.1
  # nfc_in_flutter: ^2.0.5
  flutter_barcode_scanner: ^1.0.1
  crypt: ^3.0.1
  intl: ^0.15.7
  badges: ^2.0.1
  data_table_2: ^2.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
